language: go

go:
  - 1.x

before_install:
  - sudo apt-get -qq update
  - go get -v

script:
  - go test -tags integration_tests -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
